/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author nagyg
 */
public class Foablak extends javax.swing.JFrame {

    /**
     * Creates new form Foablak
     */
    public Foablak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCimzett = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTargy = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taUzenet = new javax.swing.JTextArea();
        btnKuldes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miMegnyitas = new javax.swing.JMenuItem();
        miKilepes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miTorles = new javax.swing.JMenuItem();
        miKuldes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Címzettek:");

        tfCimzett.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tárgy: ");

        tfTargy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        taUzenet.setColumns(20);
        taUzenet.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        taUzenet.setRows(5);
        jScrollPane1.setViewportView(taUzenet);

        btnKuldes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKuldes.setText("Küldés");
        btnKuldes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKuldesActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        miMegnyitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miMegnyitas.setText("Megnyitás");
        miMegnyitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMegnyitasActionPerformed(evt);
            }
        });
        jMenu1.add(miMegnyitas);

        miKilepes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miKilepes.setText("Kilépés");
        miKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKilepesActionPerformed(evt);
            }
        });
        jMenu1.add(miKilepes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Műveletek");

        miTorles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miTorles.setText("Mezők törlése");
        miTorles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTorlesActionPerformed(evt);
            }
        });
        jMenu2.add(miTorles);

        miKuldes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miKuldes.setText("Email Küldése");
        jMenu2.add(miKuldes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCimzett)
                            .addComponent(tfTargy, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnKuldes)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCimzett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKuldes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTargy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKilepesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miKilepesActionPerformed

    private void miTorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTorlesActionPerformed
        tfCimzett.setText("");
        tfTargy.setText("");
        taUzenet.setText("");
    }//GEN-LAST:event_miTorlesActionPerformed

    private void miMegnyitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMegnyitasActionPerformed
        JFileChooser fc = new JFileChooser();
        int valasz = fc.showOpenDialog(this);
        if (valasz == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String sor;
                while ((sor = br.readLine()) != null) {
                    taUzenet.append(sor + "\n");
                }

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, "Nem találom a megadott fájlt",
                        "Hiba", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Olvasási hiba",
                        "Hiba", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_miMegnyitasActionPerformed

    private void btnKuldesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKuldesActionPerformed
        Properties prop = new Properties();
        try {
            prop.load(new FileReader("c:/prog/mail.ini"));//beállítások beolvasása
            
            Authenticator auth = new Authenticator() {//azonosításhoz
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication("minta.ember@gmail.com", "aaa aaa aaa aaa"); 
                } 
            };
            
            Session mailSession = Session.getDefaultInstance(prop, auth);
            MimeMessage message = new MimeMessage(mailSession);
            
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(tfCimzett.getText()));
            message.setSubject(tfTargy.getText());
            message.setContent(taUzenet.getText(), "text/html");
            
            Transport.send(message);
            JOptionPane.showMessageDialog(rootPane, "Elküldtem az emailt", "Siker",
                    JOptionPane.INFORMATION_MESSAGE);
            
            miTorlesActionPerformed(null);
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nem találom a megadott fájlt",
                        "Hiba", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "I/O hiba történt",
                        "Hiba", JOptionPane.ERROR_MESSAGE);
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(rootPane, "Levélküldési hiba"+ex.toString(),
                        "Hiba", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKuldesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKuldes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miKilepes;
    private javax.swing.JMenuItem miKuldes;
    private javax.swing.JMenuItem miMegnyitas;
    private javax.swing.JMenuItem miTorles;
    private javax.swing.JTextArea taUzenet;
    private javax.swing.JTextField tfCimzett;
    private javax.swing.JTextField tfTargy;
    // End of variables declaration//GEN-END:variables
}
